### ISSUE TITLE
Error: Level must be specified in init() method of each method

### ISSUE THREAD

**Issue by murilonocera** [ndunand/moodle-tool_mergeusers#126] opened 2017-07-17 20:41 UTC
Hello, 
I have installed it on Moodle 2.6, but after select users and click on "Merge User Account", It appears this error. Any idea? Thanks!

_**Level must be specified in init() method of each method**
Debug info:
Error code: codingerror
Stack trace:
    line 426 of /lib/classes/event/base.php: coding_exception thrown
    line 488 of /lib/classes/event/base.php: call to core\event\base->validate_before_trigger()
    line 231 of /admin/tool/mergeusers/lib/mergeusertool.php: call to core\event\base->trigger()
    line 135 of /admin/tool/mergeusers/index.php: call to MergeUserTool->merge()_

**Comment by designed2use** [comment] 2017-07-20 12:49
Hi murilonocera,

I think I may have got to the bottom of this, you need to add the following for backwards compatibility:
File: \admin\tool\mergeusers\classes\event\user_merged.php
Line: 50
Code: 
    protected function init() {
        $this->data['level'] = self::LEVEL_OTHER;      //  <!--- trying to fix backwards compatibility 
        $this->data['crud'] = 'u';      // Usually we perform update db queries so 'u' its ok!
        $this->data['edulevel'] = self::LEVEL_OTHER;
    }


Later versions of Moodle use the 'edulevel' instead.

Ian

**Comment by ndunand** [comment] 2017-07-20 12:53
@designed2use thanks for coming up with this solution
Should I then mark the plugin as supporting only Moodle 2.7+ ? Alternately, if I define data['level'] AND data['edulevel'], will it work without issues for all Moodle versions (i.e. 2.6 and up to 3.3) ?

**Comment by designed2use** [comment] 2017-07-20 12:57
@ndunand, We are currently running Version 2.6.11+ (Build: 20150619).

As far as I can tell it seems to have worked, but I have asked one of my administrators to test it for me to double check the users are getting merged.

I should imagine defining both wouldn't have an issue as it looks like "level" was changed to "edulevel" for some reason, but I can't be sure because I haven't tested it on later versions of moodle.

**Comment by murilonocera** [comment] 2017-07-21 13:18
Thank you! Now, it's working! :)

**Comment by jpahullo** [comment] 2017-07-24 06:57
Nice to know.

Should we close this issue @murilonocera?

**Comment by AndyNormore** [comment] 2017-12-28 18:30
@jpahullo 

I can confirm this line of code has fixed the issue. This should be added to the repo's code.

It works:

![image](https://user-images.githubusercontent.com/1661561/34419698-4689e77c-ebd3-11e7-9b51-51da544d73b0.png)

**Comment by jpahullo** [comment] 2017-12-29 12:46
Thanks for the feedback!

**Comment by jpahullo** [comment] 2018-01-12 19:37
Could you tell us if the patch #132 works for this? This way we can include in the repo.
Thanks for your time.
Jordi

**Comment by anormore** [comment] 2018-01-12 21:16
This is what has worked for me, all my user merging is now complete with this code... I will wait to see if another instance comes up and try to use your patch. But that may be weeks from now.

    protected function init() {
        $this->data['crud'] = 'u';      // Usually we perform update db queries so 'u' its ok!
        $this->data['edulevel'] = self::LEVEL_OTHER;
    }

**Comment by jpahullo** [comment] 2021-06-10 20:34
This issue was already address. Closing it.

**Closed by jpahullo** 2021-06-10 20:34 UTC
Labels: bug
