### ISSUE TITLE
course completion doesn't check after merge

### ISSUE THREAD

**Issue by gemguardian** [ndunand/moodle-tool_mergeusers#131] opened 2018-01-12 14:31 UTC
Hello, 

I think my issue is related too : Special Case #6: course_completions table has a record per user and course. Updating always the old user id for the new one is incorrect if both users appear in that group. In that case, this plugin deletes the record related to the old user. For the rest of cases, this plugin operates as usual.

But just to be sure. 

I used the merge user accounts to merge 2 accounts.  Since by accident someone handmade an account in Moodle which was not correctly connected to the ID, which ment that a new account was automatically made.

The user used the old account to do the elearing. Succeed and was awaiting his certificate. But since he made the e-learnig on the wrong (old) account no score was given back. 

I merged the old and new account and said that the new account had to stay. I see that scores get passed correctly and the activity get a check for completion. But awaiting my cron no course completion mark. 

I deleted the old account - since this was on "suspended" and we don't need it anymore and I don't want confusion. Nothing happend. 

So I wonder... is my issue related to special Case #6 and means that I cannot fix these problems by using merge user ór do I need to make a manual change in the DB to fix this? 

Thank you for your time! 
Gemma

**Comment by gemguardian** [comment] 2018-01-12 14:33
Oh before I forget. I use Moodle 3.1 >Plugin version: 1.14.1 for Moodle 2.6-3.3 (Build: 2017060801) 2017060801

**Comment by jpahullo** [comment] 2018-01-12 19:25
Hi Gemma!

Thanks for commenting and giving feedback. It's always welcome.

It has to just work as expected. Maybe it is something new on Moodle 3.1 that make this completion status work differently.

Completion status should be, as any other part of Moodle, working as expected.

Just to be clear on the remaining user after merging: the remaining user has completation status inside the course view for each activity, but this user has no completion status at course level? Where is it seen for any user please? Could you report some screenshot to detect where is the missing completion status and what value should be?

Thank you so much!

Jordi

**Comment by gemguardian** [comment] 2018-01-12 22:32
hi Jordi,

Thank you for your swift respond. Yes, the activity is check as completed in the course but it doesn't check the course completion. 

The course completion setting is set it should check course completion after the activity is completed. It works for any other user in the course but not for the merged user. 

Enclosed the requested screenshots. 

==I have not checked the DB actually==
![1cc](https://user-images.githubusercontent.com/16559999/34897943-dd928aa6-f7f0-11e7-80a3-8ac8c20919d1.png)
![2-cc](https://user-images.githubusercontent.com/16559999/34897944-ddb32db0-f7f0-11e7-9190-17e7c56b0e22.png)

**Comment by brixtee** [comment] 2019-03-27 20:14
Hello Jordi and Gemma,

I'd like to report that I'm experiencing the same issue that Gemma has reported above. I realize that the problem is likely related to a bug that has not yet been resolved. I was wondering, however, if there is an interim fix, such as, a database update to the course_completions table that would trigger course completion for the merged accounts that are inflicted by this issue. 

Thanks in advance for your support!

Brianne

**Comment by gemguardian** [comment] 2019-03-28 20:10
Hi Brianne, 

I have not checked if there was a fix in the database. We solved it at a different point since we needed to completion to signal an "event" in a different programm. 

Gem

**Comment by brixtee** [comment] 2019-04-01 16:52
Hi Gem,

Thanks for the reply. This potential bug is keeping us from assigning a badge to a student who has earned it. Any thoughts on how we might accomplish that? 

Brianne

**Comment by jpahullo** [comment] 2019-04-01 20:25
Hi!

Sorry about that. We are using it, as well as maintainig it, but maintenance is on spare time. So, there is no expected due date.

I'll try to get it priority on our job, maybe we can afford it quicker than the other way.

As always, if you or your team can develop a patch for it, it will be quicker to solve and get it done.

Thanks for your feedback and your time,

Jordi

**Comment by jpahullo** [comment] 2020-06-13 07:52
Oh yes!

I wasn't able to deal with it yet.

I'll try next week. Thank you so much for your time and patience.

We work on it at our spare time, and having recently a child, it's not easy.

See you soon.

Jordi

**Comment by jpahullo** [comment] 2021-08-01 21:03
The PR was meged which solved this issue. Closing!

**Closed by jpahullo** 2021-08-01 21:03 UTC
Labels: bug
