### ISSUE TITLE
This is a query (moodle style) error as the records have their first column identical which is not a moodle style query.

### ISSUE THREAD

**Issue by vsotirasqmplus** [ndunand/moodle-tool_mergeusers#181] opened 2020-10-21 10:10 UTC
Did you remember to make the first column something unique in your call to get_records? Duplicate value '9880' found in column 'iteminstance'.
line 1256 of /lib/dml/mysqli_native_moodle_database.php: call to debugging()
line 458 of /admin/tool/mergeusers/lib/mergeusertool.php: call to mysqli_native_moodle_database->get_records_sql()
line 271 of /admin/tool/mergeusers/lib/mergeusertool.php: call to MergeUserTool->updateGrades()
line 192 of /admin/tool/mergeusers/lib/mergeusertool.php: call to MergeUserTool->_merge()
line 135 of /admin/tool/mergeusers/index.php: call to MergeUserTool->merge()

**Comment by vsotirasqmplus** [comment] 2020-10-21 11:05
The query does not distinguish between different modules when they refer by chance to identical ID of instances but to different modules and fails

# iteminstance	itemmodule	courseid
1520	quiz	2273
1520	hvp	13263
1521	quiz	1818
1521	hvp	13263
1522	quiz	1818
1522	hvp	13263

**Comment by vsotirasqmplus** [comment] 2020-10-21 14:27
Attempt to utilise unique row ID for each record to overcome the issue

    /**
     * Update all of the target user's grades.
     * @param int $toid User id
     */
    private function updateGrades($toid, $fromid) {
        global $DB, $CFG;
        require_once($CFG->libdir.'/gradelib.php');
		$row_id = $DB->sql_concat_join("'_'", ['gi.iteminstance', 'gi.itemmodule', 'gi.courseid']) . ' rowid ';
        $sql = "SELECT DISTINCT $row_id, gi.iteminstance, gi.itemmodule, gi.courseid
                FROM {grade_grades} gg
                INNER JOIN {grade_items} gi on gg.itemid = gi.id
                WHERE itemtype = 'mod' AND (gg.userid = :toid OR gg.userid = :fromid)";

        $iteminstances = $DB->get_records_sql($sql, array('toid' => $toid, 'fromid' => $fromid));

commit ID:  873a0173

**Comment by edunao-dlm** [comment] 2021-02-23 12:06
We resolved this issue for our own use just by adding gi.id to the query:
`   $sql = "SELECT DISTINCT gi.id, gi.iteminstance, gi.itemmodule, gi.courseid`

**Comment by vsotirasqmplus** [comment] 2021-02-25 12:18
@edunao-dlm Is there an update for this plugin as there are issues on failure when grades are not released? The documentation does not provide conditions for successful existing conditions the plugin is relying upon.

**Comment by edunao-dlm** [comment] 2021-02-25 15:38
@vsotirasqmplus I ran into the same issue that you are having when using the plugin on one of our sites. Your analysis is correct. The problem is just that the gi.iteminstance value may validly be the same for more than one entry for the same user because, as you say, the iteminstance is a module-specific key.
The Moodle code requires the first column of the query to hold unique values because the get_records_sql() method returns an associative array, using the first column value as an array key.
If you read through the php code for updateGrades() you can see that it iterates over the returned records without worrying about the array key. This means that if you can add a first column to the query that contains a value that will be unique then it will work.
The gi.id value is the primary key of the gi table. it is guaranteed to be unique in the query above because of the use of the DISTINCT keyword.
I made the change that I showed in my post above:
$sql = "SELECT DISTINCT **gi.id,** gi.iteminstance, gi.itemmodule, gi.courseid
This fixed the problem for me.
I was going to report the bug but saw your post and so added my tuppence-worth in case it would be helpful.

**Comment by vsotirasqmplus** [comment] 2021-02-25 15:53
So, the question remains as to why there is no update to the repository ?

**Comment by jpahullo** [comment] 2021-06-10 21:36
The PR was merged. Closing this issue. Thanks a lot to all for your contributions!

**Closed by jpahullo** 2021-06-10 21:36 UTC
Labels: bug
