### ISSUE TITLE
Exception thrown when merging: 'Error reading from database'.

### ISSUE THREAD

**Issue by fofo2411** [ndunand/moodle-tool_mergeusers#142] opened 2018-05-21 17:48 UTC
Hi,

I am giving a try to this plugin, but it failed to merge two accounts. We do have other plugins installed and I am not sure if any of them is causing the problem. Here the error we are getting:

```
Merged «source.user» (user ID = 3336) into «target.user» (user ID = 3539)

For further reference, these results are recorded in the log id 3.
Some error occurred:
Exception thrown when merging: 'Error reading from database".

Trace:
0 /var/www/html/moodle/lib/dml/pgsql_native_moodle_database.php(242): moodle_database->query_end(false)
1 /var/www/html/moodle/lib/dml/pgsql_native_moodle_database.php(776): pgsql_native_moodle_database->query_end(false)
2 /var/www/html/moodle/admin/tool/mergeusers/lib/table/generictablemerger.php(75): pgsql_native_moodle_database->get_records_sql('SELECT id FROM ...')
3 /var/www/html/moodle/admin/tool/mergeusers/lib/mergeusertool.php(310): GenericTableMerger->merge(Array, Array, Array)
4 /var/www/html/moodle/admin/tool/mergeusers/lib/mergeusertool.php(229): MergeUserTool->_merge('3539', '3336')
5 /var/www/html/moodle/admin/tool/mergeusers/index.php(135): MergeUserTool->merge('3539', '3336')
6 {main}

Started merging at Monday, 21 May 2018, 5:20 PM
Merge took 1 seconds
```

Not sure how to get more details to troubleshoot further. Any help will be much appreciated.

**Comment by jpahullo** [comment] 2018-05-22 07:29
Thanks for reporting us the error.

It seems the problem is on the line `2` from the `Trace:`, which is giving some trouble.

Is this error being produced on every merge operation?

**Comment by jpahullo** [comment] 2019-08-16 09:04
this is probably some plugin that contains tables without the column `id`. At least, it was a common error on other feedback given to us.

I close this issue by now. If needed, we can open a new issue with more detail if it still happens.

Thansk for the feedback.

**Closed** 2019-08-16 09:04 UTC
Labels: question
