### ISSUE TITLE
events_trigger deprecated

### ISSUE THREAD

**Issue by charbusch** [ndunand/moodle-tool_mergeusers#75] opened 2015-01-04 18:48 UTC
I'm running Moodle 2.7.3+ (Build: 20141120) and get the notice that events_trigger is deprecated.  Please update.

Other than that, everything worked great, and my added plugins to config.local ran without problems

**Comment by ndunand** [comment] 2015-02-20 07:33
Closing this, as it is a duplicate of #50

**Closed by ndunand** 2015-02-20 07:33 UTC
