### ISSUE TITLE
tool_mergeusers - Users that complete the same assignment cannot be merged 

### ISSUE THREAD

**Issue by kirstymeredith** [ndunand/moodle-tool_mergeusers#117] opened 2016-09-22 13:42 UTC
Hi,

Two users who complete and get graded on the same assignment cannot be merged together:

Merge user accounts
1. Choose users to merge / ► 2. Confirm users to merge / ► 3. Merging results and log

Merged «caitmeredith» (user ID = 7) into «aaronmeredith» (user ID = 6)

For further reference, these results are recorded in the log id 3.
Some error occurred:

Exception thrown when merging: 'Error writing to database".
Duplicate entry '4-6-0-0' for key 'mdl_assisubm_assusegroatt_uix'
Trace:
#0 /u0/webroot/virtual/planinternational.dev.synergy-learning.com/www/lib/dml/mysqli_native_moodle_database.php(982): moodle_database->query_end(false)
#1 /u0/webroot/virtual/planinternational.dev.synergy-learning.com/www/admin/tool/mergeusers/lib/table/generictablemerger.php(225): mysqli_native_moodle_database->execute('UPDATE mdl_assi...')
#2 /u0/webroot/virtual/planinternational.dev.synergy-learning.com/www/admin/tool/mergeusers/lib/table/generictablemerger.php(80): GenericTableMerger->updateRecords(Array, Array, 'userid', Array, Array)
#3 /u0/webroot/virtual/planinternational.dev.synergy-learning.com/www/admin/tool/mergeusers/lib/mergeusertool.php(281): GenericTableMerger->merge(Array, Array, Array)
#4 /u0/webroot/virtual/planinternational.dev.synergy-learning.com/www/admin/tool/mergeusers/lib/mergeusertool.php(216): MergeUserTool->_merge('6', '7')
#5 /u0/webroot/virtual/planinternational.dev.synergy-learning.com/www/admin/tool/mergeusers/index.php(135): MergeUserTool->merge('6', '7')
#6 {main}

×
Merge failed! 
Your database engine supports transactions. Therefore, the whole current transaction has been rolled back and no modification has been made to your database.

Please investigate.

Thanks!

Kirsty
![unable_to_merge_2_users_same_assignment](https://cloud.githubusercontent.com/assets/22369427/18750363/bb24e0c2-80d2-11e6-9673-c50bca1e74c0.png)

**Comment by ndunand** [comment] 2016-09-22 13:45
Hi,

I think this is a duplicate of #107 . Could you check @jpahullo 's answer there and see if what he suggests fixes it?

**Comment by kirstymeredith** [comment] 2016-09-22 13:49
Thanks ndunand - will mention to the developer I am working with!

Thanks!

Kirsty

**Comment by ndunand** [comment] 2016-10-05 14:33
@kirstymeredith could you report back about this? Did the suggested solution solve this problem?

**Comment by kirstymeredith** [comment] 2016-10-05 14:39
Hi Nicolas,

I have assigned this the solution to the developer to implement - currently project management is scheduling time for him to complete the task into his work timeframe alongside other program commitements.

I will update you when the proposed solution is used and if or not it is successful.

Thanks!

Kirsty

**Comment by ndunand** [comment] 2016-10-05 14:42
great, thanks!

**Comment by jpahullo** [comment] 2016-11-03 15:24
We need to apply this patch to our Moodle 3.0 on production and worked perfectly. We should add that patch into the core of this plugin @ndunand. 

Sorry for this late answer. I am so busy last months.

**Comment by ndunand** [comment] 2016-11-03 15:38
@jpahullo OK thanks for your testing and patch! I've just pushed commit 3e5d08d to address this.

**Closed by ndunand** 2016-11-03 15:38 UTC
Labels: bug, duplicate

**Comment by jpahullo** [comment] 2016-11-03 15:42
Awesome!!!

**Comment by jpahullo** [comment] 2016-11-03 15:42
thanks!!!
